#version: '3.9'

services:
  nfs:
    image: erichough/nfs-server
    volumes:
      - ${IMAGES_PATH}:/tftpboot/images
      - ./exports:/etc/exports:ro
      - /lib/modules:/lib/modules:ro
    privileged: true
    network_mode: host
    # ports:
    #     - 2049:2049
    #     - 2049:2049/udp
    #     - 111:111
    #     - 111:111/udp
    #     - 32765:32765
    #     - 32765:32765/udp
    #     - 32767:32767
    #     - 32767:32767/udp
    environment:
      - NFS_LOG_LEVEL=DEBUG